import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import WordCloud
df=pd.read_csv(r"D:\IMDB-Movie-Data.csv")
# print(df)
print(df.head())
print(df.head().describe())
print(df.head().max())
print(df.head().min())
print(df.head().median())
print(df.head().notnull().sum())
print(df.head().isnull().sum())
print(df.info())
print(df.dropna(inplace=True))
print(df.drop(['Rank','Year','Votes','Metascore','Revenue (Millions)'],axis=1))
print(df['Runtime (Minutes)'].mean())
dfg=df.groupby(['Director'])['Title'].count().nlargest()
print(dfg)
print(df.groupby(['Genre'])['Title'].count())
y=df.groupby(['Year'])['Title'].count()
plt.plot(y)
plt.title('Number of Movies released in each Year')
plt.xlabel('Years')
plt.ylabel('Movies in each year')
f=plt.figure()
f.set_figwidth(300)
f.set_figheight(300)
plt.show()
plt.hist(df['Runtime (Minutes)'])
plt.xlabel('runtime (minutes)')
plt.ylabel('frequency')
plt.show()
print(df['Actors'].str.split(',').explode().value_counts().nlargest(3))
plt.hist(df['Rating'])
plt.xlabel('rating')
plt.ylabel('frequency')
plt.show()
print(df.loc[:,['Rating','Runtime (Minutes)']].corr())
plt.scatter(df['Revenue (Millions)'],df['Rating'])
plt.xlabel('revenue(millions)')
plt.ylabel('rating')
plt.title('relationship between revenue and rating')
plt.show()
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(' '.join(df['Title']))
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()
z=df.groupby(['Year'])['Rating'].mean()
plt.plot(z)
plt.xlabel('Year')
plt.ylabel('Average rating of each year')
plt.title('average movie rating over the years')
plt.show()
print(df.groupby(['Director','Actors']).last())
d=df.groupby(['Year'])['Runtime (Minutes)'].mean()
plt.plot(d)
plt.xlabel('Year')
plt.ylabel('Average runtime(minutes) of movies in each year')
plt.title('average runtime  of movies over the years')
plt.show()
plt.bar(df['Rating'],df['Revenue (Millions)'])
plt.xlabel('rating')
plt.ylabel('revenue (millions)')
plt.title('comparisons of rating and revenue')
plt.show()
plt.scatter(df['Rating'],df['Votes'])
plt.xlabel('rating')
plt.ylabel('votes')
plt.title('relationship of rating and votes ')
plt.show()
plt.boxplot(df['Runtime (Minutes)'])
plt.ylabel('runtime')
plt.show()
df['Runtime (Minutes)'].describe()
plt.scatter(df['Genre'],df['Rating'])
plt.xlabel('genre')
plt.ylabel('rating')
plt.show()